In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(f'../../data/subtlety_playfight_data/subtlety_data.csv',index_col=[0]) 
df

,subID,block_type,subtlety,chargeSpeeds,responses_subt_1,responses_subt_2,pred_color,responses_pf,RT,movie,trial_num,stim_dur,subt_norm,chargeSpeed_norm,accuracy,responses_pf_rev,chargeSpeed_norm_rev
14,30002,1,90.0,NaN,82.0,grey,grey,NaN,2002.0,06f1dd04-cfbc-433c-9833-32cdb01c0683,14,5692,0.500000,NaN,1.0,NaN,NaN
15,30002,1,30.0,NaN,91.0,grey,grey,NaN,1484.0,57dbdc86-9c49-4214-a908-c4a254e90229,15,5658,0.833333,NaN,1.0,NaN,NaN
16,30002,1,60.0,NaN,79.0,grey,grey,NaN,1774.0,3273fde2-4b65-4cc7-b9b3-ef2604e8a514,16,5645,0.666667,NaN,1.0,NaN,NaN
17,30002,1,90.0,NaN,28.0,black,black,NaN,2049.0,89ce6bb6-b2cb-44cb-ba57-d78ab0224625,17,5669,0.500000,NaN,1.0,NaN,NaN
18,30002,1,90.0,NaN,40.0,grey,grey,NaN,1616.0,7d6cad69-203a-49a4-9c6e-b0423a669e50,18,5620,0.500000,NaN,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,30352,1,180.0,NaN,10.0,black,grey,NaN,2928.0,1d35e834-4947-46b2-9cbd-816ea4587c6f,79,5826,0.000000,NaN,0.0,NaN,NaN
80,30352,1,30.0,NaN,82.0,grey,grey,NaN,2375.0,0a730462-ba50-4dbe-97c6-911f61a40346,80,5741,0.833333,NaN,1.0,NaN,NaN
81,30352,1,180.0,NaN,34.0,grey,black,NaN,4206.0,12a3cd27-040f-4199-9edb-5cd4bb71b3d0,81,5741,0.000000,NaN,0.0,NaN,NaN
82,30352,1,120.0,NaN,67.0,black,black,NaN,3022.0,987cd79f-7d6a-426b-8983-8bee8675f0ba,82,5746,0.333333,NaN,1.0,NaN,NaN
83,30352,1,0.0,NaN,68.0,black,black,NaN,7574.0,37b0c4a3-57d4-4b4a-9bf7-e4d2eb48cee6,83,5705,1.000000,NaN,1.0,NaN,NaN

In [3]:
df_mean = df.groupby(['subID','subtlety']).mean().reset_index()
df_mean.drop(columns=['trial_num','stim_dur','subt_norm','chargeSpeed_norm','chargeSpeeds','responses_pf_rev','chargeSpeed_norm_rev'],inplace=True)
df_mean['rating180'] = [df_mean.loc[(df_mean['subID']==subID)&(df_mean['subtlety']==180),'responses_subt_1'].values[0] for subID in df_mean['subID']]
df_mean['diff_from_180'] = df_mean['responses_subt_1']-df_mean['rating180']
df_mean

,subID,subtlety,block_type,responses_subt_1,responses_pf,RT,accuracy,rating180,diff_from_180
0,30002,0.0,1.0,94.333333,NaN,1606.833333,1.000000,2.666667,91.666667
1,30002,30.0,1.0,92.000000,NaN,1759.166667,1.000000,2.666667,89.333333
2,30002,60.0,1.0,70.000000,NaN,1760.166667,0.833333,2.666667,67.333333
3,30002,90.0,1.0,41.166667,NaN,1813.500000,1.000000,2.666667,38.500000
4,30002,120.0,1.0,6.500000,NaN,1976.666667,0.833333,2.666667,3.833333
...,...,...,...,...,...,...,...,...,...
1948,30352,60.0,1.0,72.833333,NaN,3003.833333,0.833333,24.333333,48.500000
1949,30352,90.0,1.0,57.166667,NaN,2678.833333,0.833333,24.333333,32.833333
1950,30352,120.0,1.0,43.833333,NaN,4091.333333,0.500000,24.333333,19.500000
1951,30352,150.0,1.0,37.166667,NaN,2883.000000,0.666667,24.333333,12.833333
1952,30352,180.0,1.0,24.333333,NaN,3278.166667,0.333333,24.333333,0.000000

In [4]:
df_mean.to_csv(f'../../data/subtlety_data/mean_scores_subtlety.csv')

In [14]:
df_median = df.groupby(['subID','subtlety']).median().reset_index()
df_median.drop(columns=['trial_num','stim_dur','subt_norm','chargeSpeed_norm','chargeSpeeds','responses_pf_rev','chargeSpeed_norm_rev'],inplace=True)
df_median['rating180'] = [df_median.loc[(df_median['subID']==subID)&(df_median['subtlety']==180),'responses_subt_1'].values[0] for subID in df_mean['subID']]
df_median['diff_from_180'] = df_median['responses_subt_1']-df_median['rating180']
df_median.head(14)

,subID,subtlety,block_type,responses_subt_1,responses_pf,RT,accuracy,rating180,diff_from_180
0,30002,0.0,1.0,96.5,NaN,1630.5,1.0,0.5,96.0
1,30002,30.0,1.0,95.0,NaN,1605.0,1.0,0.5,94.5
2,30002,60.0,1.0,70.5,NaN,1750.5,1.0,0.5,70.0
3,30002,90.0,1.0,34.0,NaN,1809.0,1.0,0.5,33.5
4,30002,120.0,1.0,3.5,NaN,2036.0,1.0,0.5,3.0
5,30002,150.0,1.0,5.5,NaN,2274.5,0.5,0.5,5.0
6,30002,180.0,1.0,0.5,NaN,1580.5,0.5,0.5,0.0
7,30004,0.0,1.0,99.5,NaN,3423.5,1.0,2.0,97.5
8,30004,30.0,1.0,100.0,NaN,3026.5,1.0,2.0,98.0
9,30004,60.0,1.0,99.0,NaN,2691.5,1.0,2.0,97.0
10,30004,90.0,1.0,90.5,NaN,2947.5,1.0,2.0,88.5
11,30004,120.0,1.0,71.0,NaN,4004.0,1.0,2.0,69.0
12,30004,150.0,1.0,6.0,NaN,3455.5,1.0,2.0,4.0
13,30004,180.0,1.0,2.0,NaN,3656.0,0.0,2.0,0.0

In [6]:
curvefit_traits=pd.read_csv(f'../../data/subtlety_playfight_data/curvefit_traits_merged_linearpf_onlyneccols.csv',index_col=[0])
sel_cols=['subID']
sel_cols.extend(curvefit_traits.columns[np.where(curvefit_traits.columns=='social_skill')[0][0]:])
curvefit_traits = curvefit_traits[sel_cols]
curvefit_traits

,subID,social_skill,attn_switch,img,attn_to_det,comm,posAffect,negAffect,neuroticism,extraversion,openness,agreeableness,conscientiousness,loneliness,nfriends
0,30002.0,21.0,23.0,9.0,10.0,16.000000,20.0,0.0,38.0,28.000000,31.000000,34.0,39.0,56.0,3.0
1,30004.0,21.0,20.0,9.0,15.0,15.000000,25.0,11.0,38.0,26.181818,50.000000,50.0,46.0,56.0,3.0
2,30005.0,17.0,29.0,21.0,16.0,16.000000,20.0,21.0,51.0,39.000000,40.000000,43.0,19.0,41.0,5.0
3,30006.0,8.0,10.0,5.0,10.0,3.000000,25.0,0.0,18.0,41.000000,31.000000,44.0,57.0,30.0,4.0
4,30008.0,5.0,15.0,12.0,17.0,12.222222,28.0,4.0,27.0,46.000000,42.545455,46.0,50.0,45.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,30344.0,27.0,18.0,19.0,20.0,16.000000,14.0,0.0,25.0,29.000000,49.000000,35.0,56.0,41.0,6.0
272,30345.0,15.0,14.0,6.0,13.0,5.000000,15.0,15.0,36.0,23.000000,37.000000,45.0,54.0,72.0,1.0
273,30346.0,16.0,25.0,7.0,16.0,8.000000,27.0,6.0,49.0,36.000000,36.000000,43.0,44.0,56.0,3.0
274,30348.0,8.0,7.0,4.0,11.0,2.000000,27.0,0.0,18.0,42.000000,41.000000,48.0,53.0,24.0,4.0
275,30352.0,8.0,6.0,7.0,12.0,4.000000,22.0,0.0,17.0,46.000000,47.000000,48.0,56.0,20.0,4.0

In [7]:
df_merged_mean = df_mean.merge(curvefit_traits,left_on='subID',right_on='subID')
df_merged_mean

,subID,subtlety,block_type,responses_subt_1,responses_pf,RT,accuracy,rating180,diff_from_180,social_skill,...,comm,posAffect,negAffect,neuroticism,extraversion,openness,agreeableness,conscientiousness,loneliness,nfriends
0,30002,0.0,1.0,94.333333,NaN,1606.833333,1.000000,2.666667,91.666667,21.0,...,16.0,20.0,0.0,38.0,28.0,31.0,34.0,39.0,56.0,3.0
1,30002,30.0,1.0,92.000000,NaN,1759.166667,1.000000,2.666667,89.333333,21.0,...,16.0,20.0,0.0,38.0,28.0,31.0,34.0,39.0,56.0,3.0
2,30002,60.0,1.0,70.000000,NaN,1760.166667,0.833333,2.666667,67.333333,21.0,...,16.0,20.0,0.0,38.0,28.0,31.0,34.0,39.0,56.0,3.0
3,30002,90.0,1.0,41.166667,NaN,1813.500000,1.000000,2.666667,38.500000,21.0,...,16.0,20.0,0.0,38.0,28.0,31.0,34.0,39.0,56.0,3.0
4,30002,120.0,1.0,6.500000,NaN,1976.666667,0.833333,2.666667,3.833333,21.0,...,16.0,20.0,0.0,38.0,28.0,31.0,34.0,39.0,56.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1927,30352,60.0,1.0,72.833333,NaN,3003.833333,0.833333,24.333333,48.500000,8.0,...,4.0,22.0,0.0,17.0,46.0,47.0,48.0,56.0,20.0,4.0
1928,30352,90.0,1.0,57.166667,NaN,2678.833333,0.833333,24.333333,32.833333,8.0,...,4.0,22.0,0.0,17.0,46.0,47.0,48.0,56.0,20.0,4.0
1929,30352,120.0,1.0,43.833333,NaN,4091.333333,0.500000,24.333333,19.500000,8.0,...,4.0,22.0,0.0,17.0,46.0,47.0,48.0,56.0,20.0,4.0
1930,30352,150.0,1.0,37.166667,NaN,2883.000000,0.666667,24.333333,12.833333,8.0,...,4.0,22.0,0.0,17.0,46.0,47.0,48.0,56.0,20.0,4.0
1931,30352,180.0,1.0,24.333333,NaN,3278.166667,0.333333,24.333333,0.000000,8.0,...,4.0,22.0,0.0,17.0,46.0,47.0,48.0,56.0,20.0,4.0

In [8]:
df_merged_mean.to_csv(f'../../data/subtlety_playfight_data/mean_mixedbatch_traits.csv')

In [9]:
df_merged_median = df_median.merge(curvefit_traits,left_on='subID',right_on='subID')
df_merged_median

,subID,subtlety,block_type,responses_subt_1,responses_pf,RT,accuracy,rating180,diff_from_180,social_skill,...,comm,posAffect,negAffect,neuroticism,extraversion,openness,agreeableness,conscientiousness,loneliness,nfriends
0,30002,0.0,1.0,96.5,NaN,1630.5,1.0,0.5,96.0,21.0,...,16.0,20.0,0.0,38.0,28.0,31.0,34.0,39.0,56.0,3.0
1,30002,30.0,1.0,95.0,NaN,1605.0,1.0,0.5,94.5,21.0,...,16.0,20.0,0.0,38.0,28.0,31.0,34.0,39.0,56.0,3.0
2,30002,60.0,1.0,70.5,NaN,1750.5,1.0,0.5,70.0,21.0,...,16.0,20.0,0.0,38.0,28.0,31.0,34.0,39.0,56.0,3.0
3,30002,90.0,1.0,34.0,NaN,1809.0,1.0,0.5,33.5,21.0,...,16.0,20.0,0.0,38.0,28.0,31.0,34.0,39.0,56.0,3.0
4,30002,120.0,1.0,3.5,NaN,2036.0,1.0,0.5,3.0,21.0,...,16.0,20.0,0.0,38.0,28.0,31.0,34.0,39.0,56.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1927,30352,60.0,1.0,76.0,NaN,3052.0,1.0,24.0,52.0,8.0,...,4.0,22.0,0.0,17.0,46.0,47.0,48.0,56.0,20.0,4.0
1928,30352,90.0,1.0,52.5,NaN,2519.0,1.0,24.0,28.5,8.0,...,4.0,22.0,0.0,17.0,46.0,47.0,48.0,56.0,20.0,4.0
1929,30352,120.0,1.0,54.0,NaN,3058.5,0.5,24.0,30.0,8.0,...,4.0,22.0,0.0,17.0,46.0,47.0,48.0,56.0,20.0,4.0
1930,30352,150.0,1.0,36.5,NaN,2819.0,1.0,24.0,12.5,8.0,...,4.0,22.0,0.0,17.0,46.0,47.0,48.0,56.0,20.0,4.0
1931,30352,180.0,1.0,24.0,NaN,3210.5,0.0,24.0,0.0,8.0,...,4.0,22.0,0.0,17.0,46.0,47.0,48.0,56.0,20.0,4.0

In [10]:
df_merged_median.to_csv(f'../../data/subtlety_playfight_data/median_mixedbatch_traits.csv')

In [11]:
df_merged_alltrials = df.merge(curvefit_traits,left_on='subID',right_on='subID')
df_merged_alltrials

,subID,block_type,subtlety,chargeSpeeds,responses_subt_1,responses_subt_2,pred_color,responses_pf,RT,movie,...,comm,posAffect,negAffect,neuroticism,extraversion,openness,agreeableness,conscientiousness,loneliness,nfriends
0,30002,1,90.0,NaN,82.0,grey,grey,NaN,2002.0,06f1dd04-cfbc-433c-9833-32cdb01c0683,...,16.0,20.0,0.0,38.0,28.0,31.0,34.0,39.0,56.0,3.0
1,30002,1,30.0,NaN,91.0,grey,grey,NaN,1484.0,57dbdc86-9c49-4214-a908-c4a254e90229,...,16.0,20.0,0.0,38.0,28.0,31.0,34.0,39.0,56.0,3.0
2,30002,1,60.0,NaN,79.0,grey,grey,NaN,1774.0,3273fde2-4b65-4cc7-b9b3-ef2604e8a514,...,16.0,20.0,0.0,38.0,28.0,31.0,34.0,39.0,56.0,3.0
3,30002,1,90.0,NaN,28.0,black,black,NaN,2049.0,89ce6bb6-b2cb-44cb-ba57-d78ab0224625,...,16.0,20.0,0.0,38.0,28.0,31.0,34.0,39.0,56.0,3.0
4,30002,1,90.0,NaN,40.0,grey,grey,NaN,1616.0,7d6cad69-203a-49a4-9c6e-b0423a669e50,...,16.0,20.0,0.0,38.0,28.0,31.0,34.0,39.0,56.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11587,30352,1,180.0,NaN,10.0,black,grey,NaN,2928.0,1d35e834-4947-46b2-9cbd-816ea4587c6f,...,4.0,22.0,0.0,17.0,46.0,47.0,48.0,56.0,20.0,4.0
11588,30352,1,30.0,NaN,82.0,grey,grey,NaN,2375.0,0a730462-ba50-4dbe-97c6-911f61a40346,...,4.0,22.0,0.0,17.0,46.0,47.0,48.0,56.0,20.0,4.0
11589,30352,1,180.0,NaN,34.0,grey,black,NaN,4206.0,12a3cd27-040f-4199-9edb-5cd4bb71b3d0,...,4.0,22.0,0.0,17.0,46.0,47.0,48.0,56.0,20.0,4.0
11590,30352,1,120.0,NaN,67.0,black,black,NaN,3022.0,987cd79f-7d6a-426b-8983-8bee8675f0ba,...,4.0,22.0,0.0,17.0,46.0,47.0,48.0,56.0,20.0,4.0
11591,30352,1,0.0,NaN,68.0,black,black,NaN,7574.0,37b0c4a3-57d4-4b4a-9bf7-e4d2eb48cee6,...,4.0,22.0,0.0,17.0,46.0,47.0,48.0,56.0,20.0,4.0

In [12]:
df_merged_alltrials.columns

Index(['subID', 'block_type', 'subtlety', 'chargeSpeeds', 'responses_subt_1',
       'responses_subt_2', 'pred_color', 'responses_pf', 'RT', 'movie',
       'trial_num', 'stim_dur', 'subt_norm', 'chargeSpeed_norm', 'accuracy',
       'responses_pf_rev', 'chargeSpeed_norm_rev', 'social_skill',
       'attn_switch', 'img', 'attn_to_det', 'comm', 'posAffect', 'negAffect',
       'neuroticism', 'extraversion', 'openness', 'agreeableness',
       'conscientiousness', 'loneliness', 'nfriends'],
      dtype='object')

In [13]:
df_merged_alltrials.to_csv(f'../../data/subtlety_playfight_data/mean_mixedbatch_traits_alltrials.csv')